# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

def fibonacci(max)
  fib_nums = []
  a, b, sum = 0, 1, 1

  while (sum <= max)
    fib_nums.push(sum)
    a   = b
    b   = sum
    sum = a + b
  end

  return fib_nums
end

def even_fibs(max)
  fibonacci(max).select { |i| i.even? }
end

puts "%s" % even_fibs(4_000_000).reduce(:+)
