{-
 - Each new term in the Fibonacci sequence is generated by adding the previous
 - two terms. By starting with 1 and 2, the first 10 terms will be:
 -
 - 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 -
 - By considering the terms in the Fibonacci sequence whose values do not
 - exceed four million, find the sum of the even-valued terms.
 -}

fibonacci :: Integer -> Integer
fibonacci 0 = 1
fibonacci 1 = 1
fibonacci n = iterFib 0 1 1 n where
    iterFib first second i maxVal
        | i > maxVal = second
        | otherwise  = iterFib second (first + second) (i+1) maxVal

sumEvenFibTerms :: Integer
sumEvenFibTerms = sum $ filter even $ takeWhile (< 4000000) [ fibonacci x | x <- [1..] ]
